### ISSUE TITLE
Exclude files from changlog

### ISSUE THREAD

**Issue by donavanbecker** [patrickjahns/chlgr#15]
Is there a way to exclude files from being check when running this workflow?

**Comment by patrickjahns** [comment]
Per default, the action should only check-in a file called `CHANGELOG.md` ( see https://github.com/patrickjahns/chlgr/blob/master/lib/git-helper.js#L65-L69 ). 

Did you encounter any specific issue where this behaved differently? If so, please share some more details in what scenario / use-case the action did not work as intended

**Comment by donavanbecker** [comment]
sorry I should of been more specific. So when I commit a file it looks at the commit and it runs the GitHub Action to add that commit to the the changeling. for instance this [GitHub Action](https://github.com/donavanbecker/homebridge-honeywell-home/actions/runs/64053532)

**Comment by patrickjahns** [comment]
chlgr uses the excellent [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) in order to generate the (next) entries for the changelog. 

github-changelog-generator will base the changelog on (merged) pull-requests for that certain branch you are currently running it in. It will use the pull request title and categorize them based on the labels of the pull-request. For more information on how "github-changelog-generator" does this, I suggest to also have a look at the upstream project documentation.

In my workflows (i.e. [releaseing a ansible role](https://github.com/patrickjahns/ansible-role-promtail/blob/master/.github/workflows/release.yml) ) I let the action run on the `master` branch and only if its not a pull-request containing `[RELEASE]` in the release.

Example pull-request created by the action https://github.com/patrickjahns/ansible-role-promtail/pull/6

Example run for a pull-request that triggered the generation of a changelog:
https://github.com/patrickjahns/ansible-role-promtail/runs/478218369?check_suite_focus=true

>  for instance this GitHub Action

Unfortunately the link you shared shows me an aborted run, I am not sure where there was an error

**Comment by donavanbecker** [comment]
I canceled the changelog action from running because it ran on a commit, and I only want it to run on a pull request

**Comment by patrickjahns** [comment]
If you want the action to only run on pull-requests ( before being merged ), I suggest to limit the workflow like described in here https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

**Comment by donavanbecker** [comment]
@patrickjahns this is exactly what I am looking for!! Thanks! I should of looked around!

**Comment by patrickjahns** [comment]
Glad I could help 👍
